In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("behavioral_data\\error_data.csv")

In [7]:
data = data.iloc[:, :8]
data = data.dropna(subset=['participant'])
data.loc[data['phase'] == 'learn', 'phase'] = 'study'
data[:35]

,participant,phase,condition,cue,target,response,rt,correct
0,1001.0,study,1.0,EMPIRE,STATE,KING,3457.0,2.0
1,1001.0,study,1.0,CHUNK,BLOCK,HUNK,3361.0,2.0
2,1001.0,study,1.0,GLIDE,HANG,FLY,2177.0,2.0
3,1001.0,study,1.0,SAIL,OCEAN,BOAT,2341.0,2.0
4,1001.0,study,1.0,ELEVATOR,BUILDING,UP,3464.0,2.0
5,1001.0,study,1.0,SWING,TREE,CLIMB,2857.0,2.0
6,1001.0,study,1.0,DANCER,MUSIC,SHOE,3845.0,2.0
7,1001.0,study,1.0,WELL,DONE,BAD,4030.0,2.0
8,1001.0,study,1.0,EYES,COLOR,GLASS,3764.0,2.0
9,1001.0,study,1.0,INTRODUCE,PRESENT,MEET,2180.0,2.0
10,1001.0,study,1.0,PRESCRIPTION,PILL,MEDICINE,3397.0,2.0
11,1001.0,study,1.0,CANYON,MOUNTAIN,HIGH,2268.0,2.0
12,1001.0,study,1.0,FUGITIVE,RUN,OUTLAW,4154.0,2.0
13,1001.0,study,1.0,ORDER,FORM,LAW,2222.0,2.0
14,1001.0,study,1.0,LATIN,FRENCH,AMERICA,2290.0,2.0
15,1001.0,study,1.0,ROBIN,RED,HOOD,1897.0,2.0
16,1001.0,study,1.0,PARCEL,BOX,GLASS,4731.0,2.0
17,1001.0,study,1.0,LAUNDRY,SOAP,MAT,2212.0,2.0
18,1001.0,study,1.0,COURAGEOUS,LION,BRAVE,3294.0,2.0
19,1001.0,study,1.0,CRUNCH,NOISE,BAR,3201.0,2.0
20,1001.0,study,1.0,STERN,BOAT,STRICT,4674.0,2.0
21,1001.0,study,1.0,MEASUREMENT,HEIGHT,INCH,3331.0,2.0
22,1001.0,study,1.0,DIAMETER,LENGTH,CR,4954.0,3.0
23,1001.0,study,1.0,PORTRAY,SHOW,VILLIAN,3315.0,2.0
24,1001.0,study,1.0,TEA,LEAVES,BOSTON,2971.0,2.0
25,1001.0,study,1.0,HONEYMOON,ROMANCE,WEDDING,2347.0,2.0
26,1001.0,study,1.0,SAFARI,DESERT,DESER,4835.0,1.0
27,1001.0,study,1.0,CHIMNEY,BRICK,SANTA,1980.0,2.0
28,1001.0,study,1.0,SIDE,ORDER,HUSTLE,2542.0,2.0
29,1001.0,study,1.0,DRACULA,SCARY,VAMPIRE,2810.0,2.0
30,1001.0,test,1.0,HONEYMOON,ROMANCE,ROMANCE,4347.0,1.0
31,1001.0,test,2.0,TASTY,TREAT,FOOD,6643.0,2.0
32,1001.0,test,1.0,SWING,TREE,SET,21190.0,2.0
33,1001.0,test,1.0,DIAMETER,LENGTH,LENGTH,4883.0,1.0
34,1001.0,test,1.0,CANYON,MOUNTAIN,MOUNTAIN,5486.0,1.0

In [13]:
# Splitting the DataFrame into two based on 'phase'
study_df = data[data['phase'] == 'study']
test_df = data[data['phase'] == 'test']

# Reshaping the study DataFrame
study_df = study_df.rename(columns={'response': 'study_response', 'rt': 'study_rt'})
study_df = study_df.drop(['phase', 'correct'], axis=1)

# Reshaping the test DataFrame
test_df = test_df.rename(columns={'response': 'test_response', 'rt': 'test_rt'})
test_df = test_df.drop(['phase', 'correct'], axis=1)

# Merging the DataFrames
final_df = pd.merge(study_df, test_df, on=['participant', 'cue', 'target', 'condition'], how='outer')

final_df

,participant,condition,cue,target,study_response,study_rt,test_response,test_rt
0,1001.0,1.0,EMPIRE,STATE,KING,3457.0,STATE,1610.0
1,1001.0,1.0,CHUNK,BLOCK,HUNK,3361.0,BLOCK,2348.0
2,1001.0,1.0,GLIDE,HANG,FLY,2177.0,HANG,5982.0
3,1001.0,1.0,SAIL,OCEAN,BOAT,2341.0,OCEAN,3091.0
4,1001.0,1.0,ELEVATOR,BUILDING,UP,3464.0,BUILDING,7943.0
...,...,...,...,...,...,...,...,...
3655,1069.0,2.0,THEOREM,GEOMETRY,NaN,NaN,RULE,5615.0
3656,1069.0,2.0,BISCUIT,COOKIE,NaN,NaN,COOKIE,2142.0
3657,1069.0,2.0,NATURE,FOREST,NaN,NaN,TREE,8638.0
3658,1069.0,2.0,CRITIC,ANALYZE,NaN,NaN,ANALYZE,4334.0
3659,1069.0,2.0,HOTEL,BED,NaN,NaN,BED,1615.0

In [14]:
final_df.to_csv('behavioral_data\\formatted_data.csv')